### PR TITLE
Update requirements.txt, from-source installation instructions

### PR DESCRIPTION
**Pull request by Algomorph**

### CODE REVIEW

**Comment by evertrol** [comment]
Thanks for that!

I've been looking at it a bit more, and there are a few extra changes that may be made. Perhaps you'd be willing to add those to the pull request? If not, I'll add the extra changes in due time.

I would suggest the following:

- for `requirements.txt`:
```
numpy>=1.16,<2
scipy>=1.3,<2
```
to future-proof the API.

- `setup.py` needs to have its requirements updated as well:
```
            'numpy>=1.16',
            'scipy>=1.3',
```

For development, `requirements-dev.txt` should have the Sphinx version updated:
```
sphinx>=2.1,<3
```

and finally, the note on installing the development version in the `README.rst` is probably more correct by using `requirements-dev.txt`, as follows:
```
To install in development mode::                                                     
                                                                                     
    git clone https://github.com/evertrol/scikit-tensor-py3.git                      
    cd scikit-tensor-py3                                                             
    pip3 install -r requirements-dev.txt                                             
    pip3 install 
```
instead of the current two lines.

**Comment by Algomorph** [comment]
Here you go.
I'll be migrating my old code to tensorly, hopefully the above will help others to do the same if need be.

**Comment by evertrol** [comment]
Thanks. I'll probably mentioned `tensorly` in the README, since I've only ported scikit-tensor since I needed it somewhere as a dependency. It's not really maintained or improved otherwise.

**Comment by evertrol** [comment]
I noticed `.gitignore` has a few additions; I have no idea what the `.idea/` one is, perhaps you want to remove that one? I'm okay with the egg-info line either way.
Sorry if I'm picky, I just like PRs small and clean, even if I don't really do much with this package.

**Comment by Algomorph** [comment]
`.idea/` is a directive to ignore JetBrains-generated project files, that was deliberate.

**Comment by evertrol** [comment]
Ah, right. Learn something new every day.
I guess it's a git-ignore entry that's more suitable in a user's `core.excludesfile` file.

**Comment by Algomorph** [comment]
Ok, I removed `.idea/` from gitignore (re-committed via amend/force)

**Comment by evertrol** [comment]
Looks like something went wrong: the PR now includes all the individual files in `.idea/` instead (see ["Files changed"](https://github.com/evertrol/scikit-tensor-py3/pull/27/files)).

**Comment by Algomorph** [comment]
@evertrol , Yes, I messed up trying to fix that line you were having an issue with, I ran `git add .` after removing the line. Obviously, the `.idea/` files got added. That's why the line was there to begin with. Thanks for explaining to me after the `core.excludesfile`, I wasn't even aware of that feature in git. I should have used it before I re-committed.

However, I'm out of town now and away from my machine. I'm also a PhD student working a teaching job at the University to support both my studies and my girlfriend, who's out of a job right now due to COVID. I'm tired. I'm sleeping mostly less than six hours for multiple weeks now, because of semester high-crunch time. I feel behind on my research. And I don't really need this repository for myself, since I've already migrated to `tensorly`. So wanting to help is probably not enough motivation for me to remember this when I get back home. 

So I'm closing this PR. I hope you don't mind.

**Comment by Algomorph** [comment]
Ah, just remembered: luckily, I left a TeamViewer instance running on my home machine. Let's see if I can sort this out in 30 seconds or less.

**Comment by Algomorph** [comment]
Ok, done.

**Comment by evertrol** [comment]
Cheers! All merged and done.

**Pull request merged**
